
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action FileAction;
	
	private global::Gtk.Action AboutAction;
	
	private global::Gtk.Action ProjectAction;
	
	private global::Gtk.Action AboutAction1;
	
	private global::Gtk.Action NewAction;
	
	private global::Gtk.Action OpenAction;
	
	private global::Gtk.Action SaveAction;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.MenuBar menubar1;
	
	private global::Gtk.HSeparator hseparator1;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.Button btn_Login;
	
	private global::Gtk.Button btn_Status;
	
	private global::Gtk.Fixed fixed1;
	
	private global::Gtk.Image img_logo;
	
	private global::Gtk.HSeparator hseparator3;
	
	private global::Gtk.Notebook nbk_Main;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TreeView trv_History;
	
	private global::Gtk.Label label1;
	
	private global::Gtk.Notebook nbk_Statistics;
	
	private global::Gtk.Label label4;
	
	private global::Gtk.Label label3;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.Label label2;
	
	private global::Gtk.HBox hbox4;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.Label label6;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	
	private global::Gtk.TreeView trv_Projects;
	
	private global::Gtk.HBox hbox5;
	
	private global::Gtk.Button btn_NewProject;
	
	private global::Gtk.Button btn_SaveProject;
	
	private global::Gtk.Button btn_SaveProjectAs;
	
	private global::Gtk.VSeparator vseparator1;
	
	private global::Gtk.VBox vbox4;
	
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.Label label5;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.AboutAction = new global::Gtk.Action ("AboutAction", global::Mono.Unix.Catalog.GetString ("About"), null, null);
		this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
		w1.Add (this.AboutAction, null);
		this.ProjectAction = new global::Gtk.Action ("ProjectAction", global::Mono.Unix.Catalog.GetString ("Project"), null, null);
		this.ProjectAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.ProjectAction, null);
		this.AboutAction1 = new global::Gtk.Action ("AboutAction1", global::Mono.Unix.Catalog.GetString ("About"), null, null);
		this.AboutAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
		w1.Add (this.AboutAction1, null);
		this.NewAction = new global::Gtk.Action ("NewAction", global::Mono.Unix.Catalog.GetString ("New"), null, null);
		this.NewAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("New");
		w1.Add (this.NewAction, null);
		this.OpenAction = new global::Gtk.Action ("OpenAction", global::Mono.Unix.Catalog.GetString ("Open"), null, null);
		this.OpenAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open");
		w1.Add (this.OpenAction, null);
		this.SaveAction = new global::Gtk.Action ("SaveAction", global::Mono.Unix.Catalog.GetString ("Save"), null, null);
		this.SaveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save");
		w1.Add (this.SaveAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("OLTRA");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(3));
		this.DefaultWidth = 1024;
		this.DefaultHeight = 768;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menuitem name='AboutAction' action='AboutAction'/></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.hbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator ();
		this.hseparator1.HeightRequest = 2;
		this.hseparator1.Name = "hseparator1";
		this.vbox1.Add (this.hseparator1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator1]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		this.hbox2.BorderWidth = ((uint)(5));
		// Container child hbox2.Gtk.Box+BoxChild
		this.btn_Login = new global::Gtk.Button ();
		this.btn_Login.CanFocus = true;
		this.btn_Login.Name = "btn_Login";
		this.btn_Login.UseUnderline = true;
		this.btn_Login.Label = global::Mono.Unix.Catalog.GetString ("LOGIN");
		this.hbox2.Add (this.btn_Login);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btn_Login]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btn_Status = new global::Gtk.Button ();
		this.btn_Status.Sensitive = false;
		this.btn_Status.CanFocus = true;
		this.btn_Status.Name = "btn_Status";
		this.btn_Status.UseUnderline = true;
		this.btn_Status.Label = global::Mono.Unix.Catalog.GetString ("RUN");
		this.hbox2.Add (this.btn_Status);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btn_Status]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		this.hbox2.Add (this.fixed1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.fixed1]));
		w7.Position = 2;
		// Container child hbox2.Gtk.Box+BoxChild
		this.img_logo = new global::Gtk.Image ();
		this.img_logo.Name = "img_logo";
		this.img_logo.Xalign = 0F;
		this.img_logo.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("OLTRA.logo_200.png");
		this.hbox2.Add (this.img_logo);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.img_logo]));
		w8.Position = 3;
		w8.Expand = false;
		w8.Fill = false;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hseparator3 = new global::Gtk.HSeparator ();
		this.hseparator3.HeightRequest = 2;
		this.hseparator3.Name = "hseparator3";
		this.vbox1.Add (this.hseparator3);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator3]));
		w10.Position = 3;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.nbk_Main = new global::Gtk.Notebook ();
		this.nbk_Main.CanFocus = true;
		this.nbk_Main.Name = "nbk_Main";
		this.nbk_Main.CurrentPage = 0;
		// Container child nbk_Main.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.trv_History = new global::Gtk.TreeView ();
		this.trv_History.CanFocus = true;
		this.trv_History.Name = "trv_History";
		this.GtkScrolledWindow.Add (this.trv_History);
		this.nbk_Main.Add (this.GtkScrolledWindow);
		// Notebook tab
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("LOG HISTORY");
		this.nbk_Main.SetTabLabel (this.GtkScrolledWindow, this.label1);
		this.label1.ShowAll ();
		// Container child nbk_Main.Gtk.Notebook+NotebookChild
		this.nbk_Statistics = new global::Gtk.Notebook ();
		this.nbk_Statistics.CanFocus = true;
		this.nbk_Statistics.Name = "nbk_Statistics";
		this.nbk_Statistics.CurrentPage = 0;
		// Notebook tab
		global::Gtk.Label w13 = new global::Gtk.Label ();
		w13.Visible = true;
		this.nbk_Statistics.Add (w13);
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("SUMMARY");
		this.nbk_Statistics.SetTabLabel (w13, this.label4);
		this.label4.ShowAll ();
		this.nbk_Main.Add (this.nbk_Statistics);
		global::Gtk.Notebook.NotebookChild w14 = ((global::Gtk.Notebook.NotebookChild)(this.nbk_Main [this.nbk_Statistics]));
		w14.Position = 1;
		// Notebook tab
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("STATISTICS");
		this.nbk_Main.SetTabLabel (this.nbk_Statistics, this.label3);
		this.label3.ShowAll ();
		// Container child nbk_Main.Gtk.Notebook+NotebookChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		this.nbk_Main.Add (this.hbox3);
		global::Gtk.Notebook.NotebookChild w15 = ((global::Gtk.Notebook.NotebookChild)(this.nbk_Main [this.hbox3]));
		w15.Position = 2;
		// Notebook tab
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("SETUP");
		this.nbk_Main.SetTabLabel (this.hbox3, this.label2);
		this.label2.ShowAll ();
		// Container child nbk_Main.Gtk.Notebook+NotebookChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("PROJECTS");
		this.vbox2.Add (this.label6);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label6]));
		w16.Position = 0;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.trv_Projects = new global::Gtk.TreeView ();
		this.trv_Projects.CanFocus = true;
		this.trv_Projects.Name = "trv_Projects";
		this.GtkScrolledWindow1.Add (this.trv_Projects);
		this.vbox2.Add (this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow1]));
		w18.Position = 1;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.btn_NewProject = new global::Gtk.Button ();
		this.btn_NewProject.CanFocus = true;
		this.btn_NewProject.Name = "btn_NewProject";
		this.btn_NewProject.UseUnderline = true;
		this.btn_NewProject.Label = global::Mono.Unix.Catalog.GetString ("NEW");
		this.hbox5.Add (this.btn_NewProject);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.btn_NewProject]));
		w19.Position = 0;
		w19.Expand = false;
		w19.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.btn_SaveProject = new global::Gtk.Button ();
		this.btn_SaveProject.CanFocus = true;
		this.btn_SaveProject.Name = "btn_SaveProject";
		this.btn_SaveProject.UseUnderline = true;
		this.btn_SaveProject.Label = global::Mono.Unix.Catalog.GetString ("SAVE");
		this.hbox5.Add (this.btn_SaveProject);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.btn_SaveProject]));
		w20.Position = 1;
		w20.Expand = false;
		w20.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.btn_SaveProjectAs = new global::Gtk.Button ();
		this.btn_SaveProjectAs.CanFocus = true;
		this.btn_SaveProjectAs.Name = "btn_SaveProjectAs";
		this.btn_SaveProjectAs.UseUnderline = true;
		this.btn_SaveProjectAs.Label = global::Mono.Unix.Catalog.GetString ("SAVE\nAS");
		this.hbox5.Add (this.btn_SaveProjectAs);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.btn_SaveProjectAs]));
		w21.Position = 2;
		w21.Expand = false;
		w21.Fill = false;
		this.vbox2.Add (this.hbox5);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox5]));
		w22.Position = 2;
		w22.Expand = false;
		w22.Fill = false;
		this.hbox4.Add (this.vbox2);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox2]));
		w23.Position = 0;
		w23.Expand = false;
		w23.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.vseparator1 = new global::Gtk.VSeparator ();
		this.vseparator1.WidthRequest = 3;
		this.vseparator1.Name = "vseparator1";
		this.hbox4.Add (this.vseparator1);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vseparator1]));
		w24.Position = 1;
		w24.Expand = false;
		w24.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		this.hbox4.Add (this.vbox4);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox4]));
		w25.Position = 2;
		// Container child hbox4.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		this.hbox4.Add (this.vbox3);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox3]));
		w26.Position = 3;
		this.nbk_Main.Add (this.hbox4);
		global::Gtk.Notebook.NotebookChild w27 = ((global::Gtk.Notebook.NotebookChild)(this.nbk_Main [this.hbox4]));
		w27.Position = 3;
		// Notebook tab
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("PROJECT");
		this.nbk_Main.SetTabLabel (this.hbox4, this.label5);
		this.label5.ShowAll ();
		this.vbox1.Add (this.nbk_Main);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.nbk_Main]));
		w28.Position = 4;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
